### ISSUE TITLE
VERY MINOR, but a tweek if any, The LogiX Impulse lines are completely opaque compare to the original generated in Neos

### ISSUE THREAD

**Issue by ScarsTRF** [art0007i/LogixPulseVisualizer#1]
So apparently when the Logix generates their pulse visual, it replaces the visual with a fully opaque instead of slightly alpha'd  logiX impulse line as seen below,

BEFORE:
![image](https://user-images.githubusercontent.com/23484495/190872873-d09bc141-3e8d-4372-904d-ba07f6b6ed2b.png)
AFTER:
![image](https://user-images.githubusercontent.com/23484495/190872937-7dfbb0bb-5350-41d2-a832-6c526a3cba74.png)

**Comment by ScarsTRF** [comment]
Thought to place this down, the Left is the Neos generated one, while the right side is the one generated after a pulse.
![image](https://user-images.githubusercontent.com/23484495/190873165-9b1a25c9-4a0b-463b-8079-1b97af609300.png)

**Comment by EIA485** [comment]
#2 inherently fixes this issue

**Comment by art0007i** [comment]
fixed in 1.0.2 release
